services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=ls-gEBiLelI-2816-JuPi-5933-zAkIhASA8e11
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=0
      - PERSISTENCE=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
